### PR TITLE
Support for Keycloak

### PR DESCRIPTION
**Pull request by jimbittner**
This would need to be deployed with the corresponding eva-config-web changes

### CODE REVIEW

**Comment by bmulholland** [comment]
Hi @jimbittner - apologies that it took so long to get to this PR. Two immediate questions:

1. What are the "corresponding eva-config-web changes"?
2. Does this solve the logout problem identified in https://github.com/nuxt-community/auth-module/issues/559#issuecomment-742145659 ?

**Comment by jimbittner** [comment]
No.  disregard please

**Comment by bmulholland** [comment]
Sorry - disregard what? This PR? eva-config-web changes? The logout problem?

**Comment by jimbittner** [comment]
Pr!

**Pull request closed without merging**
