### PR TITLE
docs(setup.md): add info about using module in a TypeScript project

### PR DESCRIPTION
**Pull request by ShaggyTech**
I had to search through github issues to figure out where the types files were located.  I made this quick edit to the docs to help others who are struggling with the same issue.

See #274 and #678

- add information about using this module with Typescript.
- add table of contents

### CODE REVIEW

**Comment by rommyarb** [comment]
Please merge this update, I'm using typescript too 😅

**Comment by haxoza** [comment]
Just tested and it works! 🎉   Please merge ☝️

**Comment by clorichel** [comment]
100% green to me. Thanks ShaggyTech ❤️

**Comment by kaangokdemir** [comment]
Great documentation. Please merge.

**Comment by bmulholland** [comment]
Thanks for the updates!

**Comment by bmulholland** [comment]
Hi all, just a quick note that @JoaoPedroAS51 updated the docs with some guidance for if you're using auth-next: https://github.com/nuxt-community/auth-module/pull/899

**Pull request merged**
