### PR TITLE
docs(guide): add section "creating your own scheme"

### PR DESCRIPTION
**Pull request by JoaoPedroAS51**

### CODE REVIEW

**Comment by bmulholland** [comment]
Looks like a great start! What would you think about adding a request to submit the code as a PR on this project?

**Comment by JoaoPedroAS51** [comment]
> What would you think about adding a request to submit the code as a PR on this project?

Do you mean update the demo?

**Comment by bmulholland** [comment]
No, I mean adding a note in the docs that says something like "If the schema you create might be helpful to others, please consider creating a GitHub issue or Pull Request with your configuration."

**Comment by JoaoPedroAS51** [comment]
Oh! Great idea!

**Review by pi0 — APPROVED** [review]

**Pull request merged**
