### PR TITLE
feat(local): add refresh token

### PR DESCRIPTION
**Pull request by JoaoPedroAS51**
Hi!

First of all, I would like to thank you for this awesome package! It really helps a lot!
I also would like to thank @KonoMaxi for his refresh token system https://github.com/nuxt-community/auth-module/pull/208, I used it as base to make this one. 

So, this PR will add refresh token system to local strategy.

### Features:

- [x] Works in SSR mode;
- [x] Use axios interceptor to refresh the token and retry failed requests (401);
- [x] Use axios interceptor to retry requests that conflicted with refresh token requests (401);
- [x] Wait 1s to refresh on mount to avoid request conflicts;
- [x] Default expiration time (configurable) to avoid infinite refresh;
- [x] Strategy configuration;
- [x] Configurable payload;
- [x] Prevent token refresh on mount if user is not logged in;
- [x] Logout locally on mount if token has already expired;
- [x] Uses **getProp** and **$auth.requestWith** to maintain same code style as other functions;

### Usage
Set `_scheme: 'refresh'` and configure refresh endpoint in local strategy.

#### Example:
```
auth: {
    strategies: {
        local: {
            _scheme: 'refresh',
            defaultExpirationTime: 1800,
            disableAutoRefresh: false,
            grantType: 'refresh_token',
            clientIdProperty: 'client_id', // Set it to false to not add it to payload
            grantTypeProperty: 'grant_type', // Set it to false to not add it to payload
            createdAtProperty: 'created_at',
            expiresInProperty: 'expires_in'
            endpoints: {
                login: {url: '/api/auth/login', method: 'post', propertyName: 'access_token'},
                refresh: { url: '/api/auth/refresh',  method: 'post', propertyName: 'refresh_token'},
                user: {url: '/api/auth/user', method: 'get', propertyName: 'user'},
                logout: { url: '/api/auth/logout', method: 'post'}
            }
        }
    }
},
```
**Note:** You don't need to specify each property as listed in example, as they have default values. List of default values below. Also, don't worry about the dots! If you set the property like `data.refresh_token`, it will automatically use the name after the dot in the payload!

#### Default values

```
defaultExpirationTime: 1800,
disableAutoRefresh: false,
grantType: 'refresh_token',
clientIdProperty: 'client_id',
grantTypeProperty: 'grant_type',
createdAtProperty: 'created_at',
expiresInProperty: 'expires_in'
endpoints: {
    refresh: {propertyName: 'refresh_token'}
}
```

### Bug or Suggestion
If you've found any bug or want a new functionality related to this, just make a comment and tag me!

### CODE REVIEW

**Comment by ryanwinchester** [comment]
Hi,

Will this work if I get 2 tokens from successful `login` endpoint response that I need to store? `access_token` and `refresh_token`?

Also, `propertyName` needs to be customizable, like in the current `login` endpoint configuration, I can set `propertyName: 'data.access_token'`

I can often have authentication responses like:

```json
{
  "data": {
    "access_token": "...",
    "expires_in": 1800,
    "refresh_token": "...",
    "token_type": "Bearer"
  }
}
```

**Comment by JoaoPedroAS51** [comment]
@ryanwinchester Yes, you can. Ah, and if you find any bug, let me know!

```
refresh: {
    token: 'data.refresh_token'
}
```

**Comment by JoaoPedroAS51** [comment]
Hi @ryanwinchester, I think I forgot to mention for you to use the develop branch of my fork. Sorry!

**Comment by JoaoPedroAS51** [comment]
> Hi @ryanwinchester, I think I forgot to mention for you to use the **develop** branch of my fork. Sorry!

You can use dev branch, I merged

**Comment by brolnickij** [comment]
@JoaoPedroAS51 Hello, friend! I use your fork and I have one small problem when using refresh token.
I use the following configuration in my project:
```
auth: {
  resetOnError: true,
  watchLoggedIn: true,
  vuex: {
    namespace: 'auth'
  },
  redirect: {
    login: '/auth/login',
    logout: '/auth/login',
    callback: '/auth/login',
    home: '/'
  },
  strategies: {
    local: {
      endpoints: {
        login: { url: '/auth/login', method: 'post', propertyName: 'data.token' },
        refresh: {
          url: '/auth/refresh',
          method: 'post',
          token: 'data.token',
          expiresIn: '10000'
        },
        user: { url: '/auth/info', method: 'get', propertyName: 'data' },
        logout: { url: '/auth/logout', method: 'post', propertyName: false }
      },
      refreshToken: true
    }
  }
}
```

When logging in, I have a large number of requests per second (to refresh the token) and I cannot control this. How do i fix this? I would be very grateful for your help. Thank!

image

P.S. Excuse me for my bad english

**Comment by JoaoPedroAS51** [comment]
Hi @brolnickij, thank you for contact me! That's occurring because the `expiresIn` property is expecting a property name got from response. For example `expiresIn: 'data.expiresIn'`. So you can just pass the expire time trough the response and set the property in the config! That's supposed to fix the problem. If still giving error after that, just contact me again, I'll be glad to help! :)

**Comment by JoaoPedroAS51** [comment]
Also, you gave me an idea! I could set a default expire time, that way would avoid this problem even in case of no response!

**Comment by brolnickij** [comment]
@JoaoPedroAS51 
Thank you very much for your answer!
As far as I understand, time is specified in milliseconds, right?

**Comment by brolnickij** [comment]
@JoaoPedroAS51 Оh yes, if the token expiration time could be set by default, it would be very convenient.

**Comment by JoaoPedroAS51** [comment]
Yes, milliseconds

**Comment by JoaoPedroAS51** [comment]
@brolnickij Done! Now you can set the default time using the property `defaultExpirationTime`. It accepts milliseconds. It will try to parse to int. If the value was invalid or no value was passed, it sets to 1800 milliseconds by default. :)

**Comment by JoaoPedroAS51** [comment]
@brolnickij Sorry, I said something wrong. It's not milliseconds, it's seconds. I like to use 1800 = 30m

**Comment by brolnickij** [comment]
@JoaoPedroAS51 I do not even know how to thank you for such operational assistance.
Many thanks to you, friend!

**Comment by JoaoPedroAS51** [comment]
@brolnickij I'm really glad to help! Anything you need, I'm here! :)

**Comment by mauxtin** [comment]
Great work @JoaoPedroAS51! 🎉 

It's a shame so much work that is being done by contributors is not even being addressed my the maintainers 😞

**Comment by JoaoPedroAS51** [comment]
@mauxtin Thank you so much! I'm so happy to know that my system is helping other developers! 😄 

Yeah, that's true. There is such amazing contributions, but there is no one reviewing them. 😞

**Comment by sambrezo** [comment]
Assuming the refresh_token is long lived, why not postpone the renewal until the API endpoint sends a 401/Unauthorized? For me it's a case of "Ask For Forgiveness, Not Permission". Am I missing something? Maybe my use case is different.

**Comment by JoaoPedroAS51** [comment]
Hi @sambrezo, thank you for contact me! 

I understand your point. That way would have less token refreshes. Only when really needed.

But I believe that one bad point about try to refresh only when unauthorized would be the response time. For example, if I try to save a new post and my token has already expired, it would take the time of 3 requests. First the original request (save the post in this case), then refresh the token (because it has expired) and finally retry the original request (with the new token). In my case the token expires every 30m, so it would have a long response several times.

Currently the system try to refresh the token in two cases: if the time has reached 75% of the expiration time or on access the website. That way it always have a valid token.

But if a new option `refreshOnError` will help you, I would be very happy to do so. It would have an axios interceptor that catches 401 errors, then refresh the token and retry the original request. You would still need to pass the expiration time, because it would use it as reference to check if the 401 was caused by the expired token. What do you think? :)

**Comment by sambrezo** [comment]
Hi @JoaoPedroAS51,

I can understand now why you want to keep your access_token fresh.

Thanks for offering your help! After some fiddling around I found a [solution](https://gist.github.com/sambrezo/f6af737c5928c71621b605f35f89e31d) that works for me using axios interceptors. The biggest problem was to maintain the session on a complete reload. The auth-module does not pass back any tokens that are fetched server-side, see https://github.com/nuxt-community/auth-module/pull/333. Also I am still undecided if it's good practice to store the refresh_token as a JS cookie (httpOnly=false) in the first place.

I hope we will have a reference implementation some day.

**Comment by ryanwinchester** [comment]
I think doing it both ways is good.

I think this library has a good idea:

https://github.com/esbenp/redux-refresh-token#redux-refresh-token:

> If the API call returns a 401 response then your access token probably expired. This library will try to refresh the token. Whilst refreshing it will queue up all API calls. If the refresh was successful it will retry all the queued calls. If it was not successful it will log out the user.

Since there are often more than one call per page, there can be multiple 401s, so if you only refresh on 401, and you refresh on EVERY 401, then you can be refreshing several times at once, every time a token expires?

**Comment by JoaoPedroAS51** [comment]
Ok @ryanwinchester, I will give a look at it. I reply later with more details.

**Comment by JoaoPedroAS51** [comment]
@sambrezo I'll take a look at what you sent too.

**Comment by sambrezo** [comment]
> Since there are often more than one call per page, there can be multiple 401s, so if you only refresh on 401, and you refresh on EVERY 401, then you can be refreshing several times at once, every time a token expires?

Good point

**Comment by JoaoPedroAS51** [comment]
Yep, I agree. Good point.

**Comment by JoaoPedroAS51** [comment]
> Since there are often more than one call per page, there can be multiple 401s, so if you only refresh on 401, and you refresh on EVERY 401, then you can be refreshing several times at once, every time a token expires?

@ryanwinchester @sambrezo I think I read something about it somewhere. They said this could be solved by setting a local var `isRefreshing`. That way would prevent multiple refreshes, since it only tries to refresh if `isRefreshing === false` .

**Comment by ryanwinchester** [comment]
I wonder how difficult it would be to queue all requests when `status === 401` or `isRefreshing === true`, then resend queued requests once refresh is done?

**Comment by JoaoPedroAS51** [comment]
Maybe we could save the config of requests in an array, and check if the array is empty or not after refresh.

**Comment by mheppner** [comment]
Not a huge deal, but is there a way to change the [payload](https://github.com/JoaoPedroAS51/auth-module/blob/834c07c923706842919befff1189a5be83e6fd0c/lib/schemes/local.js#L69) sent to the refresh endpoint? For example, I'd like to send the property `refresh` instead of `refresh_token`. Would an axios interceptor be the easiest way to override this?

**Comment by JoaoPedroAS51** [comment]
Hi @mheppner, thank you for contact me!

Interesting, it was a feature I was thinking about. You currently can't do that, but I can solve this easily. I'll let you know when I release the update! I think by tomorrow it will be updated. :)

**Comment by JoaoPedroAS51** [comment]
Hi @mheppner, I've just updated allowing the requested feature. Now you can easily change the payload properties by configuring `payloadProperties`. You can change `refreshToken`, `clientId` and `grantType`.

```
auth: {
    strategies: {
        local: {
            endpoints: {
                ...
                refresh: {
                    ...
                    payloadProperties: {
                        refreshToken: 'refresh',
                        clientId: 'client_id',
                        grantType: 'grant_type'
                    }
                },
                ...
            },
            refreshToken: true
        }
    }
}
```

To see a complete example, check the updated description at the top of the PR.

**Comment by mauxtin** [comment]
@JoaoPedroAS51 you should create a proper nuxt module for auth in a different repo 🥇 

Or maybe someone can give you access to this repo and release a proper 5.0.0 version with tests etc. /cc @pi0 @manniL

**Comment by JoaoPedroAS51** [comment]
@mauxtin Thank you so much, this means a lot me!

I'm not sure if I could do my own repo right now, since it's a lot of work to do and my time is short, but I would definitely help to release 5.0.0 of this repo!

**Comment by JoaoPedroAS51** [comment]
@ryanwinchester @sambrezo I'm working on a system to refresh the token on 401 errors, but I'm not sure when it will be finish, since it's not that easy. I think by the weekend I will have more time to work on it.

**Comment by yurriiy** [comment]
@JoaoPedroAS51 @ryanwinchester @sambrezo 
my version of working with local strategy and refresh token
```js
  $axios.onResponse(response => {
    if (
      response.status === 200 &&
      response.config.url === response.config.baseURL + 'auth/login'
    ) {
      store.$auth.setRefreshToken(
        store.$auth.$state.strategy,
        `Bearer ${response.data.refreshToken}`
      )
    }
    return response
  })
  
  $axios.onError(error => {
    if (code === 401) {
      if (error.config.url === error.config.baseURL + 'auth/refresh') {
        store.$auth.logout()
      } else if (store.$auth.loggedIn) {
        return refresh().then(() => {
	  // set new authorization header
          error.config.headers.Authorization = store.$auth.getToken(
            store.$auth.$state.strategy
          )
	  // repeat request
          return $axios.request(error.config)
        })
      }
      return Promise.reject(error)
    }
  }
  
  async function refresh() {
    const refreshToken = store.$auth.getRefreshToken(
      store.$auth.$state.strategy
    )
    const response = await $axios.get('auth/refresh', {
      headers: { Authorization: refreshToken }
    })
    store.$auth.setToken(
      store.$auth.$state.strategy,
      `Bearer ${response.data.accessToken}`
    )
    store.$auth.setRefreshToken(
      store.$auth.$state.strategy,
      `Bearer ${response.data.refreshToken}`
    )
    store.$auth.fetchUser() // update user if needed
  }
```

**Comment by JoaoPedroAS51** [comment]
Hi @yurriiy, thank you for sharing your code!

I still reading your code, but I've already found a really good point: **logout if error 401 was due to token refresh**
> if (error.config.url === error.config.baseURL + 'auth/refresh') {
        store.$auth.logout()
      }

I'll implement that for sure!

**Comment by JoaoPedroAS51** [comment]
@yurriiy I'm not sure, but I think your version also have this issue https://github.com/nuxt-community/auth-module/pull/325#issuecomment-485588704

**Comment by JoaoPedroAS51** [comment]
@mheppner I'm sorry, I forgot to merge the [new feature](https://github.com/nuxt-community/auth-module/pull/325/commits/b95507fe074b2472637993fd11679f6039f389e7) to dev branch. I just did it.

**Comment by JoaoPedroAS51** [comment]
@ryanwinchester @sambrezo Hey guys, I've added the [system to refresh the token on failed requests](https://github.com/nuxt-community/auth-module/pull/325/commits/e1bb2a1bd854ece9a158525ad47d3412fb95a8cb)! It works with multiple requests! Solving https://github.com/nuxt-community/auth-module/pull/325#issuecomment-485588704.
If you want, you can disable the auto refresh by setting `disableAutoRefresh` to `true`, so it will only refresh on errors. I would appreciate if you guys could test it too, to we make sure it's all working properly. Any error, bug or new idea, I'm here! 😃 

Ah, and fixed the logout when the refresh request fail. Now it only logout locally.

**Comment by yurriiy** [comment]
@JoaoPedroAS51 @ryanwinchester 
for multiple requests, i am do like this:
```js
  async function refresh() {
    const refreshToken = store.$auth.getRefreshToken(
      store.$auth.$state.strategy
    )
    const response = await $axios.get('auth/refresh', {
      headers: { Authorization: refreshToken }
    })
    store.$auth.setToken(
      store.$auth.$state.strategy,
      `Bearer ${response.data.accessToken}`
    )
    store.$auth.setRefreshToken(
      store.$auth.$state.strategy,
      `Bearer ${response.data.refreshToken}`
    )
    store.$auth.fetchUser()
  }
  function tryRepeat(request) {
    setTimeout(() => {
      if (store.state.authRefreshing === false) {
        return repeat(request)
      } else {
        tryRepeat(request)
      }
    }, 1000)
  }
  function repeat(request) {
    request.headers.Authorization = store.$auth.getToken(store.$auth.$state.strategy)
    return $axios.request(request)
  }  
  
  $axios.onError(error => {
    const code = parseInt(error.response && error.response.status)
	
	if (code === 401) {
	  if (error.config.url === error.config.baseURL + 'auth/refresh') {
		store.$auth.logout()
	  } else if (store.$auth.loggedIn) {
		if (store.state.authRefreshing === false) {
		  store.commit('setAuthRefreshing', true)
		  return refresh().then(() => {
			store.commit('setAuthRefreshing', false)
			return repeat(error.config)
		  })
		} else {
		  tryRepeat(error.config)
		}
	  }
	  return Promise.reject(error)
	}
  }
```
where authRefreshing - flag in store
first request causes refresh, all other wait

**Comment by yurriiy** [comment]
also i found out that after store.$auth.setToken, sometimes request send with old token
workaround:
$axios.defaults.headers.common.Authorization = <new token>
store.$auth.setToken(store.$auth.$state.strategy, <new token>)

**Comment by rprins** [comment]
Hi, first of all: thank you for writing this code, this is exactly what my current project needed.

There's just one thing I would like to ask. Is it possible to change which attributes are sent with the payload when requesting a new refreshToken? The api I'm working with doesn't accept any additional attributes apart from refreshToken.

**Comment by JoaoPedroAS51** [comment]
@rprins Hi! I'm glad to know I helped you!
About your question, yes, you can change payload properties. I've released an update that allows to change them, you can see an example here https://github.com/nuxt-community/auth-module/pull/325#issuecomment-486022058

**Comment by rprins** [comment]
Wow, that was a quick response, haha.
Yes, I meant to remove something from the payload. All I want to send right now is the refreshToken. There is no need for me to send the clientId or grantType.
For now I just removed lines 95 and 96 from lib/schemes/local.js so I can get it working. :)

**Comment by JoaoPedroAS51** [comment]
@rprins HAHA! Ok, got it. I'll work on this today, then by tomorrow I release the update allowing this. ;)

**Comment by JoaoPedroAS51** [comment]
@rprins Done. Now you can remove `clientId` and `grantType` by setting them to `false` in `payloadProperties`.

```
auth: {
    strategies: {
        local: {
            endpoints: {
                ...
                refresh: {
                    ...
                    payloadProperties: {    
                        clientId: false,
                        grantType: false
                    }
                },
                ...
            },
            refreshToken: true
        }
    }
}
```

**Comment by rprins** [comment]
@JoaoPedroAS51 thank you for taking the time to update the code. I just tested it out and everything seems to be working like it should. :)

**Comment by JoaoPedroAS51** [comment]
I'm glad to help! :)

**Comment by louistiti** [comment]
@JoaoPedroAS51 thanks for the latest updates!

**Comment by JoaoPedroAS51** [comment]
Hi guys, I've just fixed some errors caused by the [system that refresh the token on failed requests](https://github.com/nuxt-community/auth-module/pull/325#issuecomment-487148958). Please, anyone who is using my fork after that [commit](https://github.com/nuxt-community/auth-module/pull/325/commits/e1bb2a1bd854ece9a158525ad47d3412fb95a8cb), update to the latest version. :)

**Comment by brolnickij** [comment]
@JoaoPedroAS51 Hello friend, once more..
I would like to thank you for the great work you have done.
For some reason, after the last update of changes in your fork, I have duplicated tokens in all requests.
Before the latest updates, I had no such trouble.
Screenshot 2019-05-23 at 12 53 36
what could be the problem? thank you!

**Comment by JoaoPedroAS51** [comment]
@brolnickij Hi! Thank you! :)

I'm aware about that. It's strange because my last update added a line that prevent the token from refresh twice, and I haven't changed anything related to login. Also in my project I don't see this issue. But I'm investigating. 

Could you help me by saying the last commit you were using before update?

**Comment by pi0** [comment]
@JoaoPedroAS51 @brolnickij this issue is related to the latest axios-module update (nuxt-community/axios-module#250)

**Comment by JoaoPedroAS51** [comment]
@pi0 Ah! That's why I'm not having trouble in my project... Thank you!

**Comment by brolnickij** [comment]
@pi0
Thank! 
Why do you think "nuxt-auth" hasn't been updated for so long and everyone has to use forks?

**Comment by pi0** [comment]
@brolnickij Sorry for that. I was busy for maintaining other stuff. Working with @JoaoPedroAS51 to merge it ASAP and also plan to dedicate more time on auth this week :)

**Comment by brolnickij** [comment]
@JoaoPedroAS51 @pi0 Thanks again for your hard work, guys, you make this world a better place!

**Comment by JoaoPedroAS51** [comment]
Hey guys! We have been refactoring the refresh system, and now it has its own scheme. We also moved the endpoint options to scheme. Please, check the updated docs in the top of the page!

**Comment by JoaoPedroAS51** [comment]
Hey guys! We are now working on another [branch](https://github.com/nuxt-community/auth-module/tree/feat/refresh) and [PR](https://github.com/nuxt-community/auth-module/pull/361). Check it out here #361 

We have been improving and refactoring the refresh scheme, so check the new docs at the new PR before update!

The major improvement is the interceptor. Now we intercept the **requests** instead of the **errors**. That way we check if the token has expired before send the request and if so, it refreshes the token. So no more 401 errors!

I'm also keeping the branch up to date with the latest releases!

**Note:** This branch will not be updated anymore. Please, use the new one!

**Comment by manniL** [comment]
Closing here as work continues on https://github.com/nuxt-community/auth-module/pull/361 :relaxed: 	Thanks so far!

**Pull request closed without merging**
