### PR TITLE
Fix updating config after refresh

### PR DESCRIPTION
**Pull request by DudaevAR**

### CODE REVIEW

**Comment by DudaevAR** [comment]
Does anyone know how to pull `AxiosOptions` from `nuxt-community/axios-module` https://github.com/nuxt-community/axios-module/blob/668866b6e5e66cf3ccf2a6857e65395e90cf8bd9/types/index.d.ts#L26

**Comment by DudaevAR** [comment]
@JoaoPedroAS51 ping

**Comment by JoaoPedroAS51** [comment]
Hi @DudaevAR! Thank you for your PR! 
`HTTPRequest` and `HTTPResponse` have been improved as you suggested, in #690 😊
(Alias `HTTPRequest` to `AxiosRequestConfig` and `HTTPResponse` to `AxiosResponse`)

**Comment by DudaevAR** [comment]
Hi @JoaoPedroAS51 
Please update `config.headers ` on `config.headers.common` in `_getUpdatedRequestConfig` as in my PR, this fixes the refresh token update problem

**Comment by JoaoPedroAS51** [comment]
@DudaevAR Are you having a problem with refresh? 
This is made by purpose. If we use `config.header.common` we can't get the updated token.

**Comment by DudaevAR** [comment]
@JoaoPedroAS51 Yes, I have problem after refresh.
I checked and when calling the function, the config is of type AxiosOptions from 
https://github.com/nuxt-community/axios-module/blob/668866b6e5e66cf3ccf2a6857e65395e90cf8bd9/types/index.d.ts#L26

**Comment by DudaevAR** [comment]
Okey, why then in `_requestHasAuthorizationHeader` uses `config.headers.common`

**Pull request closed without merging**
