### PR TITLE
v4.6.0

### PR DESCRIPTION
**Pull request by pi0**
### Bug Fixes

- Add audience to requests (#222, #239) (@kazazes)
- Set extended for body-parser urlencoded to prevent the deprecation warning (#199) (@tobyryuk)
- Remove trailing slash from redirect paths (#235) (@sghgh1996)
- Handle mounted errors during init (#234) (@gotoin)
- Prevent `loggedIn` being incorrectly set to true (#346) (@glennjacobs, @alexbonhomme, @t-matsu-j)
- Replace deprecated `process.browser` with `process.client` (#269) (@sschadwick)
- Preserve query params when redirecting (#193) (@mathieutu)

### New Features

- Add `resetOnError` (#197) (@ishitatsuyuki)
- Add `setUserToken` (#278) (@dgwight)
- Use strategy tokenName for `requestWith` (#301) (@terion-name, @farnabaz) 
- Support passing extra query params (#358) (@rchl)
- Generate nounce for `id_token` response type (#298) (@jefer590)
- Add guest option in auth middleware (#264) (@ricardogobbosouza)
- Accept `state` and `nonce` as `login` args (e5579e9)
- Support `onRedirect` hook (#185) (@paulgv)
- Improve storage and support server-set cookies (#360) (huge thanks to @MathiasCiarlo)

### Docs

Thanks to @3vilArthas, @af12066, @ansidev, @aretw0, @chettapong, @drewjbartlett, @f213, @farnabaz, @jahangirahmad, @LeCoupa, @NinthAutumn, @PJLindsay, @potato4d, @rodgarcia, @sgarner, @shadowlion, @sobolevn, @timmyg, @tomsaleeba  for contributing to the docs :heart:

### CODE REVIEW

**Comment by pi0** [comment]
@assoft dev changes are little more than small fixes. so it would be better to use semver/minor.

**Comment by pi0** [comment]
All docs are now online at master.

**Comment by Anaphase** [comment]
FYI the live docs are reflecting features added in this pull request (e.g. [`setUserToken`](https://auth.nuxtjs.org/api/auth.html#setusertoken-token) and [`resetOnError`](https://auth.nuxtjs.org/api/options.html#resetonerror)). Since these changes are not currently published, seeing these in the docs was a little confusing as a newcomer!

**Comment by pi0** [comment]
Thanks, @Anaphase. I'll try to trigger a release until tomorrow.

**Pull request merged**
