### PR TITLE
fix(oauth2): restore callback handling on static sites

### PR DESCRIPTION
**Pull request by jakul**
Fixes https://github.com/nuxt-community/auth-module/issues/299.
Fixes https://github.com/nuxt-community/auth-module/issues/452.

This fix works for my static Nuxt site, logging into Auth0.

### CODE REVIEW

**Comment by marconi1992** [comment]
@pi0 Do you know when a new version with be published with this fix?

**Comment by pi0** [comment]
I is already published :)

**Comment by MathiasCiarlo** [comment]
@pi0 @jakul does the handle callback always render server side first? Or are there instances where it only happens client side (ie. no real callback)?

If we are certain it always happens ssr, I propose we change the line to the following:
```js
    // Fetching token with authorization code should only be done server side
    if (process.client) {
      // Redirect to home
      this.$auth.redirect('home', true)
      return true
    }
```
This way we can keep @Atinux's change which drastically improves the performance.

**Comment by pi0** [comment]
> does the handleCallback always render server side first?

Not in SPA mode.

**Comment by MathiasCiarlo** [comment]
Okay, can we know which mode we are running? I want to do this:
```js
if (universalMode && process.client) {
```

**Comment by bjesus** [comment]
@jakul do you maybe have some example repo? I'm still seeing this issue with a static site using auth0. When running `yarn dev` everything works fine, but when using `generate --spa` and then serving it - I can't login.

**Comment by Strahinja** [comment]
@bjesus This isn't working for my setup (universal/static) even with 4.7.0. `yarn dev` works (more or less) fine, but uploaded `dist` from `yarn generate` just hangs on callback page.

**Comment by bjesus** [comment]
@Strahinja Are you using Auth0? My config looks like this and it's working, statically generated and served from Netlify:

```
  auth: {
    redirect: {
      callback: "/login",
      logout: false,
      home: "/home",
      login: false
    },
    rewriteRedirects: false,
    strategies: {
      auth0: {
        domain: "auth.mydomain.com",
        client_id: my_client_id,
        audience: "https://mydomain.auth0.com/api/v2/"
      }
    }
  },
```

`/login` is a page on my system that redirects to `/home` with a simple `_this.$router.push("/reports");`

**Comment by Strahinja** [comment]
Nope, I'm not using Auth0. My website repo is at https://github.com/Strahinja/strahinja-org. This is the relevant part of my `nuxt.config.js`:

```js
import authConfig from './auth.config.js';
// ...
auth: {
        cookie: {
            options: {
                expires: 7, // days
            },
        },
        localStorage: false,
        plugins: [ { src: '~/plugins/auth.js', mode: 'client' } ],
        strategies: {
            local: false,
            google: {
                client_id: authConfig.google.client_id,
            },
            facebook: {
                client_id: authConfig.facebook.client_id,
            },
            github: {
                client_id: authConfig.github.client_id,
                client_secret: authConfig.github.client_secret,
            },
            twitter: {
                client_id: authConfig.twitter.client_id,
            },
        },
        redirect: {
            login: '/login',
            logout: '/',
            callback: '/login/callback',
        }
    },
```

`/login/callback` is just a page showing a spinner, much like the `/callback` from the auth-module demo. I also include `middleware: ['auth']` on my '/login' page. I didn't add any explicit redirection to `/login/callback`, but it still works with `yarn dev`, auth-module picks up parameters from query/hash and then redirects further. My `plugins/auth.js` checks if user is logged in, calls `getToken()` and `fetchUserOnce()`, and finally updates the login log in my database.

I feel that Nuxt statically generating `/login/callback` might be an issue. I'll try to test that when I have time and report here.

**Comment by Strahinja** [comment]
I tried setting

```js
    generate: {
        //...
        exclude: [
            /login/,
        ],
    },
```

but unfortunately nothing changes, auth-module still doesn't pick up parameters from the query/hash.

**Comment by Strahinja** [comment]
I just tried adding
```js
middleware: ['auth'],
```
to `/login/callback` in my project and now Google login works, but Facebook login and Github login (with code flow) still don't.

**Pull request merged**
