### PR TITLE
chore: update all dependencies

### PR DESCRIPTION
**Pull request by JoaoPedroAS51**

### CODE REVIEW

**Comment by bmulholland** [comment]
A bunch of issues have been reported with Axios > 5.12.1, e.g. https://github.com/nuxt-community/auth-module/issues/809.

Perhaps we could fix it to 5.12.1 for now?

**Comment by JoaoPedroAS51** [comment]
> A bunch of issues have been reported with @nuxtjs/axios > 5.12.1, e.g. #809.

Oh, I forgot about that. 

> Perhaps we could fix it to 5.12.1 for now?

Yeah, I agree.

**Comment by JoaoPedroAS51** [comment]
Just a note, the real issue is updating axios `0.19.2` to `0.20.0` (that's the difference in `@nuxtjs/axios > 5.12.1`). Maybe we can do some research to understand what changed and why is causing issues in auth module?

**Comment by JoaoPedroAS51** [comment]
> Perhaps we could fix it to 5.12.1 for now?

I think we should do the same thing for auth v5 until we find out what happened.

**Pull request merged**
