### PR TITLE
Set extended for body-parser urlencoded

### PR DESCRIPTION
**Pull request by tobyryuk**
Removes the deprecation warning

### CODE REVIEW

**Comment by pi0** [comment]
Sorry for late merge. Thanks :)

**Comment by vhf** [comment]
It would be good to have this included in the next npm release :)

**Comment by vhf** [comment]
v4.5.2 and v4.5.3 got released since this PR got merged, unfortunately they don't include this change.

**Comment by pi0** [comment]
This PR has been published in [v4.6.0](https://github.com/nuxt-community/auth-module/releases/tag/v4.6.0)

**Pull request merged**
