### PR TITLE
WIP: merge next into dev

### PR DESCRIPTION
**Pull request by pi0**
I've separated new changes into this branch for final reviews.

### CODE REVIEW

**Comment by robsontenorio** [comment]
@pi0 can you consider including improvements from #188 ?

**Comment by sobolevn** [comment]
Any ideas about when this is planned to be merged? Thanks!

**Comment by sschadwick** [comment]
@pi0 Looking forward to seeing this merged! Any timeline on approval?

**Comment by syffs** [comment]
@farnabaz any plan to merge this ?

**Comment by manniL** [comment]
@pi0 I guess we can close here?

**Comment by pi0** [comment]
This PR is partially landed in dev. API scheme will be added on top of latest updates.

**Pull request closed without merging**
