### PR TITLE
docs: migration to docus documentation

### PR DESCRIPTION
**Pull request by Geminii**
Migration to new beautiful documentation aka Docus ❤️

### CODE REVIEW

**Comment by bmulholland** [comment]
Looks like we're going to keep this pending until some theme issues are fixed, per https://github.com/nuxt-community/axios-module/pull/466#issuecomment-763493863

**Comment by GrahamSH-LLK** [comment]
Is this good to merge?

**Comment by bmulholland** [comment]
No, the PR I linked isn't merged either, so the theme issues are presumably outstanding.

**Comment by GrahamSH-LLK** [comment]
> No, the PR I linked isn't merged either, so the theme issues are presumably outstanding.

I mean, the last activity there was in January, so who knows. I'll comment there.

**Comment by bmulholland** [comment]
Yep exactly. I'm not in the loop about what's happening with the docs so I can't say that it's ready otherwise.

**Comment by Geminii** [comment]
Not ready for the moment. I will check and ask near Atinux for more details.

**Comment by bmulholland** [comment]
Waiting for docus v2: https://github.com/nuxt-community/axios-module/pull/466#issuecomment-950782278

**Pull request closed without merging**
