### PR TITLE
fix: Allow dots on relative urls

### PR DESCRIPTION
**Pull request by lightglitch**
Fix for #1038

### CODE REVIEW

**Comment by DakoMumladze** [comment]
This PR is very important, please review and merge guys

**Comment by DakoMumladze** [comment]
Hi guys, any updates about this? 😒

**Comment by DakoMumladze** [comment]
Hi guys, how are you? what's the status of this PR? are you going to merge it?

**Comment by lightglitch** [comment]
@bmulholland can you please review and merge please.

**Comment by bmulholland** [comment]
I have been summoned :)

This seems straightforward enough :)

**Comment by lightglitch** [comment]
@bmulholland  Thank you

**Pull request merged**
