### PR TITLE
feat: generate nounce for `id_token` response type

### PR DESCRIPTION
**Pull request by jefer590**
## Justification
When I tried to use this module with `id_token` in the `response_type` using the auth0 strategy this error appeared:
image
 
Upon further investigation, I read that this `nonce` is required in the request to Auth0 (or maybe Oauth2 as a whole) to mitigate replay attacks 

## References
https://openid.net/specs/openid-connect-core-1_0.html#NonceNotes
https://tools.ietf.org/html/draft-ietf-oauth-v2-threatmodel-06#section-4.6.2
https://auth0.com/docs/api-auth/tutorials/nonce

### CODE REVIEW

**Comment by ianfortier** [comment]
I have the same issue, anyone found a fix?

**Comment by CrackDavid** [comment]
Needs definitely a merge - Auth0 schema is useless without it

**Comment by akaNightmare** [comment]
Anyone, who can merge it - please merge!

**Comment by ysaakpr** [comment]
Why it is not been merged yet or if any changes required must be updated.

**Comment by ianfortier** [comment]
Anyone else still needs this? 👍

**Comment by ysaakpr** [comment]
I moved away to https://github.com/IdentityModel/oidc-client-js, because I found that the auth-module have very less active contribution happening, and the other is well maintained.

**Comment by metasean** [comment]
If I'm reading correctly, this _functionality_ (but from a different PR) is actually included in @nuxtjs/auth v. 4.5.3

https://github.com/nuxt-community/auth-module/pull/318

The relevant code changes are here:
https://github.com/nuxt-community/auth-module/pull/318/commits/a515af2acec3977ccf516e32bc82f9cf1809d282

But I'm still wrapping my head around all this, and the code between this PR and that one are distinct enough, that I'm not actually sure if this is fixing the same problem or not.  🤷‍♂️

**Comment by pi0** [comment]
Thanks, @jefer590 for this PR and fix. Will be released soon by v4.6.0 (#356)

**Comment by pi0** [comment]
This PR has been published in [v4.6.0](https://github.com/nuxt-community/auth-module/releases/tag/v4.6.0)

**Pull request merged**
