### PR TITLE
fix: check that header have not been sent before setting cookie in response

### PR DESCRIPTION
**Pull request by auenkind**
Checks that headers have not been sent before setting a cookie in the server response.

### CODE REVIEW

**Comment by bmulholland** [comment]
@auenkind Can you please detail what problem this is solving?

**Comment by auenkind** [comment]
> 
> 
> @auenkind Can you please detail what problem this is solving?

When you use server side rendering and refresh-tokens nuxt-auth tries to set the cookies in the response. Sometimes the headers of the response have already been sent and a server-side exception is thrown. The fix prevents this server-side exception.

**Comment by bmulholland** [comment]
The headers vs cookie ordering sounds like the real issue, and this is just sweeping the problem under the carpet. Why not fix the root of the problem?

**Comment by auenkind** [comment]
> 
> 
> The headers vs cookie ordering sounds like the real issue, and this is just sweeping the problem under the carpet. Why not fix the root cause of the header vs cookie timing?

yes absolutely, i`ll create a bug. There is nearly no error handling in the setcookie method at the moment so this "fix" might be better than the current unhandled exception.

**Comment by bmulholland** [comment]
Hey, thanks! I really appreciate the investigation. What would help us most would be if you could post a working repro, or do investigation of when/why this happens. At the very least, please include lots of details on what you're seeing - when you can repro, when you can't, etc.

With regards to this PR, I don't think we should have error handling specifically for an internal bug, and definitely not one that ignores the problem - that will just make the problem harder to find/fix. I'll close this PR and look forward to continuing this discussion on the bug report.

Thanks again :)

**Comment by JoaoPedroAS51** [comment]
Hi @bmulholland! There is already an opened issue for this #802 

It's easy to reproduce. Just need to set auth middleware with `auth: 'guest'` in a page.

**Pull request closed without merging**
