### PR TITLE
Feat/refresh

### PR DESCRIPTION
**Pull request by ruudboon**
Merged dev into branch
Fixed lint errors
Refactored timeout on refresh token to fix lint error

### CODE REVIEW

**Comment by emilsgulbis** [comment]
Installed `github:ruudboon/auth-module#feat/refresh` on local app and used config as mentioned https://github.com/nuxt-community/auth-module/pull/361#issue-282213943
did a manual testing - 
1. login works
2. storing of refresh token works
3. but looks like Vuex `auth` store doesnt update and redirect doesnt work as expected

**Comment by emilsgulbis** [comment]
Jumped into source code and found out that instead of using `auth.strategies.local.endpoints.user.propertyName` to read data from user endpoint you should set `auth.strategies.local.user`

**Comment by ruudboon** [comment]
I spoke to @pi0 last year ;) Some major rework is needed to support this. Internally ky is used in nuxt and it has `beforeRetry` hook. It makes sense to use that while keeping axios support.

**Comment by emilsgulbis** [comment]
Also just found out that refresh token auth doesnt work on SSR - for example when refreshing browser. Page stucks

**Comment by ruudboon** [comment]
@pi0 Can you give us a status update? Is there stuff going on to move to ky? Are there ways we can contribute to speed things up?

**Comment by kisuka** [comment]
Any updates on this?

**Comment by JoaoPedroAS51** [comment]
Closing here as these changes have been implemented. Thanks @ruudboon!

**Pull request closed without merging**
