### PR TITLE
feat: Session Storage Support

### PR DESCRIPTION
**Pull request by Intevel**
Added session storage support, idea: #1322

### CODE REVIEW

**Comment by Intevel** [comment]
@bmulholland Can you take a look at this, its a nice feature.

**Comment by bmulholland** [comment]
I do this on a voluntary basis, so I get to what I want when I'm able. Please don't @ ping me unless there's something urgent.

**Comment by Intevel** [comment]
Oh okay, sorry.

**Comment by bmulholland** [comment]
It's okay, I appreciate your PR and I'm sure you're eager to get it out. No hard feelings, just setting my boundaries :)

**Comment by bmulholland** [comment]
Thanks again for this. Just took a look and the work seems good and comprehensive -- I appreciate the docs etc.

I think the nuxt team has some plans for storage management (centralizing how cookies, local storage, and state in general is handled) so I'm checking with others to see if this works with that planned direction. I'll let you know when I hear back.

**Comment by mrfilippoff** [comment]
will you add that feature?

**Pull request closed without merging**
