### PR TITLE
allow to add a function to redirection configuration

### PR DESCRIPTION
**Pull request by Yama-Tomo**
allow to add a function to redirection configuration of `nuxt.config.js` 

that takes `Nuxt Context` as argument.

we can possible to implement redirection more flexibly.

## Use-case

* redirect to the previous page after login without using cookie (relate #[134](https://github.com/nuxt-community/auth-module/issues/134#issuecomment-408333700)

nuxt.config.js
```javascript
module.exports = 
  .....
  auth: {
    .....
    rewriteRedirects: false, // do not call $storage.setUniversal('redirect', xxxxx)
    redirect: {
      login: (ctx) => `/signin?redirect=${encodeURIComponent(ctx.route.fullPath)}`,
      home: (ctx) => {
        if (ctx.query.redirect) {
          return ctx.query.redirect
        }
        return '/home'
      }
    }
  }
}
```

* with nuxt-i18n module

nuxt.config.js
```javascript
module.exports = 
  .....
  auth: {
    .....
    redirect: {
      // generate path using localePath method
      login: (ctx) => ctx.app.localePath('signin'),
      home: (ctx) => ctx.app.localePath('home')  
    }
  }
}
```

### CODE REVIEW

**Comment by frbuceta** [comment]
something new?

**Comment by theo-bittencourt** [comment]
My project utilizes `nuxt-auth` and `nuxt-i18n` and the `rewriteRedirects` is not working properly because the URLs are prefixed by the locale codes (i.e. `/en-US/auth/login`; `pt-BR/auth/login`.

So I think this feature could help in cases like mine. BTW is a very frequent scenario. :-P

**Comment by Yama-Tomo** [comment]
@theo-bittencourt `onRedirect` will help you.
This is useful to customize the URL to be redirected
(I closed this because I found out about it.)

Here's a sample I'm actually using.
For your reference.
https://github.com/Yama-Tomo/vue-vuex-typescript-sample/blob/nuxt/nuxt.config.ts#L120
https://github.com/Yama-Tomo/vue-vuex-typescript-sample/blob/nuxt/src/plugins/auth/redirect.ts

**Comment by theo-bittencourt** [comment]
@Yama-Tomo I really, really thank you! 

I had to change some pieces but worked great.

**Change 1**
* ```ctx.query.redirect``` --> ```app.router.currentRoute.query```
My ```ctx.query``` was empty. Can't figure out why.

* ```String(ctx.query.redirect)``` -> ```decodeURIComponent(query.redirect)```

The final:
```javascript
  ...
    if (to === redirect.home) {
      const query = app.router.currentRoute.query

      if (query.redirect) {
        const redirectUrl = decodeURIComponent(query.redirect)
        delete query.redirect
        return redirectUrl
      }
  ...
```

**Change 3** (note: was not breaking anything)
``` ...{ redirect: AuthRedirect }```  -->  ```redirect: AuthRedirect```
https://github.com/Yama-Tomo/vue-vuex-typescript-sample/blob/nuxt/nuxt.config.ts#L120

**Change 4** - An additional stuff.
As my project needs locale prefixed URLs, I had to handle links with no locale, i.e. Links from transactional email.
https://gist.github.com/5e089a4888849243bd76ea929b35ead6

o/

**Pull request closed without merging**
