### PR TITLE
Fixes nuxt-community/auth-module#133

### PR DESCRIPTION
**Pull request by nysos3**

### CODE REVIEW

**Comment by pi0** [comment]
Thanks, @nysos3 for this PR. 

For making SSR logout working we may need to clear token cookie using [setCookie](https://github.com/nysos3/auth-module/blob/ccc0ea7257880174c5118f0cb198e4a11fd9cd17/lib/core/storage.js#L171) which is currently implemented for client-side only.

**Comment by nysos3** [comment]
This actually fixes SSR logout without needing to implement setCookie on the server, as nuxt transfers state to the client, and since the logout method now sets user/tokens to false, they don't register as null or undefined, and are then properly propagated to the cookies/localStorage by the client.

**Comment by pi0** [comment]
But token is not being stored in the Vuex (https://github.com/nysos3/auth-module/blob/ccc0ea7257880174c5118f0cb198e4a11fd9cd17/lib/core/storage.js#L99) how can it be propagated? :D

**Comment by nysos3** [comment]
Ah, I'm using `token.` as the prefix instead of `_token.`. What's the point of keeping it out of the store? Immutability outside of the auth module? Or simply to keep it hidden?

**Comment by pi0** [comment]
@nysos3 Keeping secure things as hidden as possible indeed. If it is being stored in vuex it will be in every SSR response and also `window.$nuxt.$store`. Cookies are a secure mechanism for transferring such things. 

I totally agree with your current changes in this PR but it would be much much better if we also use `set-cookie` header for set/unset tokens from the server side.

**Comment by nysos3** [comment]
@pi0, I still don't understand what good keeping it out of vuex does.

So you're protecting from javascript that has access to the window object? In all modern browsers, cross domain iframes are isolated and don't have access to the same window object, and therefore none of this auth data.

I can still hit:
`window.$nuxt.$options.$auth.$storage._state['_token.local']` 
or:
`window.$nuxt.$options.$axios.defaults.headers.common.Authorization`

or simply:
 ```oldHeader = XMLHttpRequest.prototype.setRequestHeader;
XMLHttpRequest.prototype.setRequestHeader = function(header,value){
    if(header === 'Authorization')
        alert(value);
    oldHeader.apply(this, arguments);
}```

or even more simply: `window.document.cookie`

Cookies are just as insecure.

**Comment by nysos3** [comment]
@pi0 Shall I make another PR to set the default token prefix to just `token.`? 😃

**Comment by pi0** [comment]
I'm not sure and still thinking using cookies would be a better option.

**Comment by nysos3** [comment]
Then why implement the store or localStorage at all?

Also, what about those that have disabled cookies, and rely on vuex-persisted-state instead, since that's a package built for multi-storage, where as this is an Auth module, allowing for the separation of responsibilities?

**Comment by nysos3** [comment]
For the record, I agree that we need to be able to modify cookies server side as well, but we also need support for `false` user/token. This pull request achieves that much. Maybe I can work out another for handling cookies in SSR after this one.

**Pull request merged**
