### PR TITLE
update scheme documentation where user.property documentation needs updated

### PR DESCRIPTION
**Pull request by whardier**
This changes the documentation so that False is understood for `user.property` for local/refresh schemes as disable.. and `'.'` is understood as the root of the JSON reply.

### CODE REVIEW

**Comment by bmulholland** [comment]
Hey, thanks for the update! It's great to make improvements like this to the docs.

I'm new to the project so I'm looking at this with fresh eyes, and my read of the code is a little bit different than you've documented here. The proper way to resolve this is to write tests to confirm... If you have the inclination to add those, it would be very welcome - otherwise I'll merge this PR once I get the time to do it myself.

Thanks again :)

**Comment by whardier** [comment]
Dec is a busy month.   I'll revisit testing (had planned on it) early next year unless you beat me to it.

**Comment by whardier** [comment]
It is a bit confusing how token.property and user.property are very similar in nature functionality wise and documented identical.. but a false value means something very different.

**Comment by bmulholland** [comment]
Yeah, great points, I agree with you. Thanks again for the PR :)

**Comment by JoaoPedroAS51** [comment]
Closing here, as `getResponseProp` was deprecated in #1006

**Pull request closed without merging**
