### PR TITLE
Add default samesite option for cookies

### PR DESCRIPTION
**Pull request by hareku**
For https://github.com/nuxt-community/auth-module/issues/465

### CODE REVIEW

**Comment by pi0** [comment]
Hi & Thanks for making this PR @hareku. Indeed this is a good practice but I'm worried about not introducing a breaking change. This will be the default for sure in the next major release. But meanwhile, what do you think about documenting it or show a warning to users to explicitly set `cookie.options.samesite` with `lax` as recommended value?

**Comment by hareku** [comment]
Thank you for your feedback @pi0.
As you say, this PR contains a breaking change. This is not just a problem with this library, so I don't make any changes. Thank you.

**Comment by dappiu** [comment]
_Firefox 76.0.1_ started to show a warning on `auth.*` cookies.

```
Some cookies are misusing the recommended “sameSite“ attribute.

Cookie “auth.strategy” will be soon rejected because it has the “sameSite” 
attribute set to “none” or an invalid value, without the “secure” attribute. 
To know more about the “sameSite“ attribute, read 
https://developer.mozilla.org/docs/Web/HTTP/Cookies

...
```

**Comment by onlime** [comment]
Why was this issue ever closed? In latest `@nuxtjs/auth-next@5.0.0-1595976864.509d9d6`, the `sameSite` attribute is still set to "none". This is the default for the following cookies:

- `auth.strategy`
- `auth._token.*`
- `auth._token_expiration.*`

and I don't see any way of configuring this differently, changing it to `lax`

**Comment by onlime** [comment]
ok, I figured out that this is already implemented and working as expected, `nuxt.config.js`:

```js
    auth: {
        cookie: {
            options: {
                sameSite: 'lax',
            },
        },
    },
```

Please add cookie option `sameSite` to v5 documentation under https://dev.auth.nuxtjs.org/api/options#cookie

**Comment by adrianwix** [comment]
Still not added... 2 years later

**Pull request closed without merging**
