### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by herbertscruz**
Solved issue #6 and accept suggestion of the issue #3.

### CODE REVIEW

**Comment by jhesgodi** [comment]
@herbertscruz Thank you for taking the time for submitting this improvement, its great.

I have a question:
Recently I added my own middleware for `auth`, and I'm looking for a way to exclude routes from the `auth` middleware.

```javascript
const options = {
  loginRoute: '/login',
  excluded: [
    'index',
    'login'
    // ...
  ]
}

export default function authMiddleware ({ store, redirect, route }) {
  // If user not logged in, redirect default login
  const notExcluded = !options.excluded.includes(route.name);
  const notLoggedIn = !store.getters['auth/loggedIn'];

  if (notExcluded && notLoggedIn) {
    return redirect(options.loginRoute)
  }
}
```


 Is there a proper way to do it from the nuxt.config.js rather than skipping them on the middleware itself?

**Comment by herbertscruz** [comment]
Hello @jhesgodi

Thanks for the recognition of my work, it's a pleasure to help.

If you want a reusable component, you can include it in nuxt.config.js. However, I think this solution is particular to each application, because in most cases it will be necessary to verify the role of the user and each application has its particularities.

**Comment by herbertscruz** [comment]
Hello @pi0 ,

have you encountered any problems in this PR?

**Comment by pi0** [comment]
Emm no Just didn't find some time to test changes on  my local env. Sorry for delaying. Will merge and release now so we can check it later :)

**Pull request merged**
