### PR TITLE
fix(refresh): prevent duplicating refresh token in parallel requests

### PR DESCRIPTION
**Pull request by trandaison**
Fix issue: https://github.com/nuxt-community/auth-module/issues/1772 and https://github.com/nuxt-community/auth-module/issues/1743

Screen Shot 2022-11-01 at 11 28 06

### CODE REVIEW

**Comment by trandaison** [comment]
Hi @bmulholland,

Can we get this merged and release? Thank you!

**Comment by bmulholland** [comment]
There’s not much point: a rewrite is coming soon

**Comment by bmulholland** [comment]
But sure, can merge if you add a comment explaining what this code is doing and why.

**Comment by trandaison** [comment]
@bmulholland Thanks for reviewing.
I added some comment to explain the code. Can you merge it now? Thanks!

> a rewrite is coming soon

Can't wait to see the new version of this module.

**Review by bmulholland — APPROVED** [review]

**Pull request merged**
