### PR TITLE
fix(utils): check if `holder` is `object` in `getProp` util

### PR DESCRIPTION
**Pull request by CraftingGamerTom**
Added a check for both ways a string can be defined. This fixes an exception when the server returns a string instead of an object. See #699 for more information.

### CODE REVIEW

**Review by JoaoPedroAS51 — APPROVED** [review]
Hi @CraftingGamerTom! Thank you for the PR! Nice work 😄 

My PR #941 was for `dev` branch, yours is for `master` :)

What do you think about using `typeof holder !== 'object'`?

**Comment by CraftingGamerTom** [comment]
It won't work / fix the problem I solved in #699 . 

But I'm sure that you guys will sort that out cause confused how I can have a PR for 5 months ago and no responses from anyone and then out of nowhere that contribution gets scooped up into a different PR for the exact same issue and it gets approved and I get asked if it is okay 😂

**Comment by JoaoPedroAS51** [comment]
We were busy on other things in the last few months, but we're here now. I'm so sorry for the delay.

Why it won't work / fix the problem you solved?

**Comment by JoaoPedroAS51** [comment]
@CraftingGamerTom Sorry, I think we had a misunderstanding. What I was trying to say is that my PR #941 was merged into v5 (`dev` branch). Then, I would like to use your PR to merge into v4 (`master` branch). And, I would like to know if you agree about changing here to `typeof holder !== 'object'` as well, so we keep same code on both.

**Comment by CraftingGamerTom** [comment]
_I owe you an apology. I'm sorry. Not only did I misunderstand the plan, I also jumped the gun and misunderstood your (much more elegant) solution. I was admittedly butt-hurt because it is not apparent that you created a PR for any other reason other than to solve the same problem but not consider my PR. Then yours was approved quickly. I also did not realize you were the original author of issue #699 . I didn't see any other issues your PR was related to and assumed you came out of nowhere on #699 and just remade my PR pointed at the correct branch. I'm not very familiar with the contribution process to the nuxt-community but I think I've learned a lot today._

-----

Okay, I will put this back to pointing at master. I believe I did intend this for dev? It was so long ago. I don't remember. 
I also had a hard time reproducing my original error as I thought I used your proposed solution and still had errors but after much more testing than I am willing to admit to I still cannot reproduce any errors. I'll make a commit to match your solution.

Also, I originally did not think your solution would work because I had a false understanding that a String object (created with a constructor) would not work with your solution - my testing showed it would work. Nice work on this.

Some more info on this:
https://stackoverflow.com/questions/17256182/what-is-the-difference-between-string-primitives-and-string-objects-in-javascrip

I also updated the codepen with some better examples
https://codepen.io/craftinggamertom/pen/zYrZLvN

**Comment by JoaoPedroAS51** [comment]
@CraftingGamerTom No problem! And thank you for having time to find and fix this issue :)

**Comment by JoaoPedroAS51** [comment]
@CraftingGamerTom Sorry again for the confusion. Just fixed the other PR/commit https://github.com/nuxt-community/auth-module/commit/23ecb31943d8aab25fa325d06d517b0c565c2d9a, marking you as author :)

**Pull request merged**
