### PR TITLE
fix: ExpiredAuthSessionError #1118

### PR DESCRIPTION
**Pull request by bordagabor**

### CODE REVIEW

**Comment by JoaoPedroAS51** [comment]
Hi @bordagabor! Thank you for taking time to work on this issue! :)

I reviewed your PR and I believe this still not being the real fix. Cookies/localStorage being set to `false` when token is `false` is expected. And changing the token behaviour could introduce potential breaking changes to other schemes.

The issue reported in #1118 is related to Authorization header, so I believe the bug we are looking for is something that set/change the Authorization header. To be more specific, somewhere where it converts `false` to `string`, or doesn't check for `false` boolean.

You can add me on discord, then we can work together on this, what do you think? Joao Pedro AS51#1284

**Comment by bordagabor** [comment]
@JoaoPedroAS51 I just closed the issue, you can find details in the issue ticket. Thanks for reviewing my PRs :) I going to reject it because the issue was in my local logic.

**Comment by JoaoPedroAS51** [comment]
@bordagabor I'm happy to know it's working now! :)

**Comment by goldengecko** [comment]
I encountered this problem and it turned out that when I was using jsonwebtoken to generate my token at the back end, for the expiresIn arg I was passing a string instead of a number (I got it from process.env). If you do this, it assumes you are specifying the number of milliseconds before expiry rather than the number of seconds.

**Pull request closed without merging**
